export type SkillItem = {
  slug: string;
  title: string;
  audience: string;
  outcome: string;
  tools: string[];
  difficulty: "入门" | "进阶" | "专业";
  timeSaved: string;
  monetization: "低" | "中" | "高";
  steps: string[];
  promptExample: string;
  relatedPack: string;
  href: string;
  installUrl: string;
  installLabel: string;
};

export type SkillBranch = {
  slug: string;
  title: string;
  description: string;
  color: string;
  skills: SkillItem[];
};

export const skillBranches: SkillBranch[] = [
  {
    slug: "productivity",
    title: "效率办公插件",
    description: "让 Agent 连接文档、邮箱、日程和知识库，自动处理重复办公任务。",
    color: "from-blue-500 to-cyan-500",
    skills: [
      {
        slug: "notion-agent-plugin",
        title: "Notion 知识库插件",
        audience: "个人知识管理者、内容团队、项目团队",
        outcome: "让 AI Agent 读取、整理和更新 Notion 页面，把资料沉淀成可搜索知识库。",
        tools: ["Notion", "AI Agent", "API"],
        difficulty: "进阶",
        timeSaved: "每周 2-5 小时",
        monetization: "中",
        steps: ["授权 Notion 工作区", "选择可访问页面", "设定整理规则", "让 Agent 自动归档资料", "定期生成知识库摘要"],
        promptExample: "适合用于自动整理会议记录、客户需求、选题库、项目资料和 SOP 文档。",
        relatedPack: "Notion 知识库插件方案",
        href: "/skills/notion-agent-plugin",
        installUrl: "https://www.notion.com/connections",
        installLabel: "Notion 官方连接",
      },
      {
        slug: "gmail-agent-plugin",
        title: "Gmail 邮件助手插件",
        audience: "销售、客服、自由职业者、企业管理者",
        outcome: "让 Agent 辅助分类邮件、提取待办、生成回复草稿和跟进提醒。",
        tools: ["Gmail", "Google Calendar", "AI Agent"],
        difficulty: "进阶",
        timeSaved: "每天 30-60 分钟",
        monetization: "中",
        steps: ["连接 Gmail", "设定邮件分类规则", "识别重要客户和待办", "生成回复草稿", "同步跟进提醒"],
        promptExample: "适合用于客户跟进、报价回复、会议安排、投诉处理和销售线索整理。",
        relatedPack: "邮件自动化插件方案",
        href: "/skills/gmail-agent-plugin",
        installUrl: "https://workspace.google.com/marketplace",
        installLabel: "Google 插件市场",
      },
      {
        slug: "google-drive-agent-plugin",
        title: "Google Drive 文件插件",
        audience: "团队负责人、行政人员、内容团队、自由职业者",
        outcome: "让 Agent 读取、整理和分类云端硬盘文件，自动找到合同、报价、素材和项目资料。",
        tools: ["Google Drive", "Docs", "AI Agent"],
        difficulty: "入门",
        timeSaved: "每周 2-4 小时",
        monetization: "中",
        steps: ["连接 Google Drive", "选择可访问文件夹", "设定资料分类规则", "让 Agent 搜索和总结文件", "生成项目资料索引"],
        promptExample: "适合用于合同整理、客户资料查找、素材归档、项目文件汇总和团队知识库搭建。",
        relatedPack: "Google Drive 文件整理插件方案",
        href: "/skills/google-drive-agent-plugin",
        installUrl: "https://workspace.google.com/marketplace",
        installLabel: "Google 插件市场",
      },
      {
        slug: "google-calendar-agent-plugin",
        title: "Google Calendar 日程插件",
        audience: "销售、顾问、管理者、课程老师",
        outcome: "让 Agent 读取日程、生成会议提醒、安排跟进事项，并把任务同步到日历。",
        tools: ["Google Calendar", "Gmail", "AI Agent"],
        difficulty: "入门",
        timeSaved: "每天 15-30 分钟",
        monetization: "中",
        steps: ["连接日历账号", "授权读取日程", "设定会议提醒规则", "生成待办和跟进清单", "同步新日程"],
        promptExample: "适合用于销售跟进、课程预约、会议提醒、客户回访和个人时间管理。",
        relatedPack: "AI 日程管理插件方案",
        href: "/skills/google-calendar-agent-plugin",
        installUrl: "https://workspace.google.com/marketplace",
        installLabel: "Google 插件市场",
      },
      {
        slug: "slack-team-plugin",
        title: "Slack 团队消息插件",
        audience: "远程团队、客服团队、项目经理、创业公司",
        outcome: "让 Agent 读取频道消息、提炼待办、总结讨论内容，并提醒负责人处理关键事项。",
        tools: ["Slack", "AI Agent", "任务管理"],
        difficulty: "进阶",
        timeSaved: "每周 2-6 小时",
        monetization: "中",
        steps: ["连接 Slack 工作区", "选择频道", "设定关键词和任务规则", "自动生成频道摘要", "输出负责人待办"],
        promptExample: "适合用于团队周报、客服问题归类、项目会议纪要、跨部门沟通和远程协作。",
        relatedPack: "Slack 团队协作插件方案",
        href: "/skills/slack-team-plugin",
        installUrl: "https://slack.com/apps",
        installLabel: "Slack App Directory",
      },
      {
        slug: "airtable-database-plugin",
        title: "Airtable 数据表插件",
        audience: "运营人员、内容团队、轻量 CRM 使用者、项目团队",
        outcome: "让 Agent 读取和更新 Airtable 数据表，把客户、选题、库存和项目进度变成可自动处理的数据。",
        tools: ["Airtable", "API", "AI Agent"],
        difficulty: "进阶",
        timeSaved: "每周 2-5 小时",
        monetization: "高",
        steps: ["连接 Airtable Base", "选择数据表", "设定字段含义", "让 Agent 读取和更新记录", "生成运营报表"],
        promptExample: "适合用于客户名单整理、内容排期、库存追踪、项目管理和轻量业务后台。",
        relatedPack: "Airtable 运营数据库插件方案",
        href: "/skills/airtable-database-plugin",
        installUrl: "https://airtable.com/marketplace",
        installLabel: "Airtable Marketplace",
      },
      {
        slug: "trello-task-plugin",
        title: "Trello 任务看板插件",
        audience: "小团队、自由职业者、项目经理、运营人员",
        outcome: "让 Agent 读取看板任务、自动整理优先级、生成进度摘要和下一步行动。",
        tools: ["Trello", "AI Agent", "任务看板"],
        difficulty: "入门",
        timeSaved: "每周 1-3 小时",
        monetization: "低",
        steps: ["连接 Trello", "选择看板", "读取任务卡片", "自动整理优先级", "生成项目进度报告"],
        promptExample: "适合用于内容排期、项目跟进、任务复盘、团队周会和个人待办管理。",
        relatedPack: "Trello 任务整理插件方案",
        href: "/skills/trello-task-plugin",
        installUrl: "https://trello.com/power-ups",
        installLabel: "Trello Power-Ups",
      },
      {
        slug: "asana-project-plugin",
        title: "Asana 项目管理插件",
        audience: "项目经理、增长团队、产品团队、远程团队",
        outcome: "让 Agent 读取项目任务、识别延期风险、生成状态报告，并提醒成员更新进度。",
        tools: ["Asana", "AI Agent", "项目管理"],
        difficulty: "进阶",
        timeSaved: "每周 2-5 小时",
        monetization: "中",
        steps: ["连接 Asana 项目", "读取任务和负责人", "识别延期和阻塞", "生成项目日报", "输出下一步计划"],
        promptExample: "适合用于产品迭代、营销项目、客户交付、跨部门协作和远程团队管理。",
        relatedPack: "Asana 项目管理插件方案",
        href: "/skills/asana-project-plugin",
        installUrl: "https://asana.com/apps",
        installLabel: "Asana Apps",
      },
      {
        slug: "dropbox-file-plugin",
        title: "Dropbox 文件整理插件",
        audience: "设计团队、摄影师、内容团队、企业资料管理员",
        outcome: "让 Agent 查找、分类和总结 Dropbox 文件，减少人工翻找素材和资料的时间。",
        tools: ["Dropbox", "AI Agent", "文件管理"],
        difficulty: "入门",
        timeSaved: "每周 1-4 小时",
        monetization: "中",
        steps: ["连接 Dropbox", "选择文件夹", "建立命名和分类规则", "自动查找资料", "生成文件摘要"],
        promptExample: "适合用于素材库整理、客户文件归档、项目资料搜索和团队共享资料管理。",
        relatedPack: "Dropbox 文件整理插件方案",
        href: "/skills/dropbox-file-plugin",
        installUrl: "https://www.dropbox.com/app-integrations",
        installLabel: "Dropbox App Center",
      },
    ],
  },
  {
    slug: "development",
    title: "开发部署插件",
    description: "让 Agent 连接代码仓库、数据库和部署平台，帮你完成开发与上线流程。",
    color: "from-violet-600 to-slate-900",
    skills: [
      {
        slug: "github-agent-plugin",
        title: "GitHub 代码仓库插件",
        audience: "开发者、独立站长、AI 创业者",
        outcome: "让 Agent 读取代码、创建分支、提交修改、追踪 Issue，并协助生成 PR。",
        tools: ["GitHub", "Codex", "Cursor"],
        difficulty: "专业",
        timeSaved: "每周 3-8 小时",
        monetization: "高",
        steps: ["连接 GitHub 账号", "授权目标仓库", "让 Agent 分析项目结构", "执行代码修改", "提交 commit 或 PR"],
        promptExample: "适合用于网站改版、Bug 修复、功能迭代、文档更新和自动化维护。",
        relatedPack: "GitHub Agent 开发插件",
        href: "/skills/github-agent-plugin",
        installUrl: "https://github.com/marketplace?type=apps",
        installLabel: "GitHub Marketplace",
      },
      {
        slug: "vercel-deploy-plugin",
        title: "Vercel 自动部署插件",
        audience: "网站站长、SaaS 创业者、前端开发者",
        outcome: "让 Agent 连接 Vercel 项目，查看部署状态、分析构建错误和协助上线。",
        tools: ["Vercel", "Next.js", "GitHub"],
        difficulty: "进阶",
        timeSaved: "每次部署 20-60 分钟",
        monetization: "高",
        steps: ["连接 Vercel 项目", "读取部署日志", "定位构建错误", "修复代码后推送", "确认生产环境状态"],
        promptExample: "适合用于 Next.js 网站上线、域名绑定、构建失败排查和自动部署流程。",
        relatedPack: "Vercel 部署插件方案",
        href: "/skills/vercel-deploy-plugin",
        installUrl: "https://vercel.com/marketplace",
        installLabel: "Vercel Marketplace",
      },
      {
        slug: "supabase-database-plugin",
        title: "Supabase 数据库插件",
        audience: "独立开发者、AI 工具站、会员系统项目",
        outcome: "让 Agent 协助设计数据库表、执行 SQL、查看日志和管理潜在客户资料。",
        tools: ["Supabase", "Postgres", "AI Agent"],
        difficulty: "专业",
        timeSaved: "每周 2-6 小时",
        monetization: "高",
        steps: ["连接 Supabase 项目", "设计数据表结构", "执行 SQL 迁移", "检查 API 权限", "查看数据和日志"],
        promptExample: "适合用于会员系统、收藏功能、线索表单、自动生成内容和后台管理。",
        relatedPack: "Supabase 数据库插件方案",
        href: "/skills/supabase-database-plugin",
        installUrl: "https://supabase.com/partners/catalog",
        installLabel: "Supabase 集成目录",
      },
      {
        slug: "jira-issue-plugin",
        title: "Jira Issue 管理插件",
        audience: "开发团队、产品经理、测试团队、外包项目团队",
        outcome: "让 Agent 读取 Issue、整理需求、生成验收标准，并辅助追踪 Bug 和开发进度。",
        tools: ["Jira", "AI Agent", "开发流程"],
        difficulty: "专业",
        timeSaved: "每周 3-6 小时",
        monetization: "高",
        steps: ["连接 Jira 项目", "读取 Issue 和 Sprint", "整理需求和优先级", "生成验收标准", "输出开发进度摘要"],
        promptExample: "适合用于需求拆解、Bug 分类、Sprint 复盘、测试用例生成和项目交付管理。",
        relatedPack: "Jira 开发流程插件方案",
        href: "/skills/jira-issue-plugin",
        installUrl: "https://marketplace.atlassian.com",
        installLabel: "Atlassian Marketplace",
      },
      {
        slug: "figma-design-plugin",
        title: "Figma 设计稿插件",
        audience: "设计师、产品经理、前端开发者、品牌团队",
        outcome: "让 Agent 读取设计上下文、整理页面文案、生成设计标注和前端实现建议。",
        tools: ["Figma", "AI Agent", "设计协作"],
        difficulty: "进阶",
        timeSaved: "每周 2-5 小时",
        monetization: "中",
        steps: ["连接 Figma 文件", "选择页面或组件", "提取文案和结构", "生成实现说明", "输出设计检查清单"],
        promptExample: "适合用于落地页文案、设计交接、组件说明、产品原型整理和前端开发沟通。",
        relatedPack: "Figma 设计协作插件方案",
        href: "/skills/figma-design-plugin",
        installUrl: "https://www.figma.com/community/plugins",
        installLabel: "Figma 插件社区",
      },
    ],
  },
  {
    slug: "marketing",
    title: "营销增长插件",
    description: "让 Agent 连接表单、客户资料和内容平台，帮助网站更快获得线索。",
    color: "from-rose-500 to-violet-600",
    skills: [
      {
        slug: "lead-capture-plugin",
        title: "潜在客户收集插件",
        audience: "AI 工具站、课程卖家、企业服务团队",
        outcome: "在网站中收集邮箱、需求和感兴趣产品，为后续销售和付费转化做准备。",
        tools: ["Supabase", "表单", "邮件系统"],
        difficulty: "入门",
        timeSaved: "持续收集线索",
        monetization: "高",
        steps: ["设计领取入口", "收集邮箱和兴趣标签", "保存到数据库", "后台查看客户", "后续发送产品或服务邀请"],
        promptExample: "适合用于免费资料领取、等待名单、课程预售、企业咨询和工具推荐转化。",
        relatedPack: "线索收集插件方案",
        href: "/skills/lead-capture-plugin",
        installUrl: "mailto:hello@agentzhan.com?subject=我想获取线索收集插件方案",
        installLabel: "获取方案",
      },
      {
        slug: "seo-content-plugin",
        title: "SEO 内容增长插件",
        audience: "站长、内容团队、AI 网站运营者",
        outcome: "让 Agent 定期生成主题建议、草稿、标签和 SEO 描述，帮助网站持续扩充页面。",
        tools: ["Vercel Cron", "OpenAI", "Supabase"],
        difficulty: "专业",
        timeSaved: "每天 1-2 小时",
        monetization: "高",
        steps: ["读取已有内容", "分析缺少主题", "生成新内容草稿", "质量评分和去重", "保存为草稿或发布"],
        promptExample: "适合用于 AI 工具站、行业知识库、模板站和长期 SEO 内容增长。",
        relatedPack: "SEO 自动内容插件方案",
        href: "/skills/seo-content-plugin",
        installUrl: "mailto:hello@agentzhan.com?subject=我想获取 SEO 内容增长插件方案",
        installLabel: "获取方案",
      },
      {
        slug: "hubspot-crm-plugin",
        title: "HubSpot CRM 插件",
        audience: "销售团队、B2B 企业、顾问服务、课程销售",
        outcome: "让 Agent 读取客户阶段、整理跟进记录、生成销售邮件和下一步成交动作。",
        tools: ["HubSpot", "CRM", "AI Agent"],
        difficulty: "进阶",
        timeSaved: "每天 30-90 分钟",
        monetization: "高",
        steps: ["连接 HubSpot", "读取联系人和交易阶段", "整理客户需求", "生成跟进话术", "提醒销售下一步动作"],
        promptExample: "适合用于客户跟进、销售漏斗管理、报价邮件、线索评分和成交复盘。",
        relatedPack: "HubSpot 销售自动化插件方案",
        href: "/skills/hubspot-crm-plugin",
        installUrl: "https://ecosystem.hubspot.com/marketplace/apps",
        installLabel: "HubSpot App Marketplace",
      },
      {
        slug: "wordpress-content-plugin",
        title: "WordPress 内容发布插件",
        audience: "站长、SEO 团队、博客运营者、内容营销团队",
        outcome: "让 Agent 辅助生成文章草稿、SEO 标题、摘要和标签，并协助发布到 WordPress。",
        tools: ["WordPress", "SEO", "AI Agent"],
        difficulty: "进阶",
        timeSaved: "每周 3-8 小时",
        monetization: "高",
        steps: ["连接 WordPress", "设定栏目和标签", "生成文章草稿", "检查 SEO 描述", "保存草稿或发布"],
        promptExample: "适合用于行业博客、产品教程、长尾关键词文章、内容站和联盟营销页面。",
        relatedPack: "WordPress SEO 内容插件方案",
        href: "/skills/wordpress-content-plugin",
        installUrl: "https://wordpress.org/plugins/",
        installLabel: "WordPress 插件目录",
      },
      {
        slug: "zapier-automation-plugin",
        title: "Zapier 自动化插件",
        audience: "无代码创业者、运营人员、小企业老板、自由职业者",
        outcome: "让 Agent 通过 Zapier 连接上千种应用，把表单、邮件、CRM 和通知流程自动串起来。",
        tools: ["Zapier", "无代码自动化", "AI Agent"],
        difficulty: "入门",
        timeSaved: "每周 2-10 小时",
        monetization: "高",
        steps: ["选择触发应用", "设定自动化动作", "加入 AI 处理步骤", "测试工作流", "上线并监控结果"],
        promptExample: "适合用于线索入库、邮件通知、订单提醒、内容分发和跨工具数据同步。",
        relatedPack: "Zapier 自动化工作流方案",
        href: "/skills/zapier-automation-plugin",
        installUrl: "https://zapier.com/apps",
        installLabel: "Zapier App Directory",
      },
      {
        slug: "make-automation-plugin",
        title: "Make 自动化插件",
        audience: "自动化顾问、运营团队、电商团队、SaaS 团队",
        outcome: "让 Agent 配合 Make 设计多步骤自动化流程，处理数据转换、通知、入库和内容生成。",
        tools: ["Make", "Webhook", "AI Agent"],
        difficulty: "专业",
        timeSaved: "每周 3-12 小时",
        monetization: "高",
        steps: ["建立 Scenario", "连接触发器", "加入 AI 处理模块", "设定条件分支", "监控执行日志"],
        promptExample: "适合用于复杂自动化、订单处理、内容生产流水线、客户通知和数据同步。",
        relatedPack: "Make 自动化插件方案",
        href: "/skills/make-automation-plugin",
        installUrl: "https://www.make.com/en/integrations",
        installLabel: "Make Integrations",
      },
    ],
  },
  {
    slug: "business",
    title: "企业流程插件",
    description: "把客服、销售、报表、资料整理等工作接入 Agent，形成可交付的企业 AI 工作流。",
    color: "from-amber-500 to-orange-600",
    skills: [
      {
        slug: "customer-service-plugin",
        title: "AI 客服知识库插件",
        audience: "电商卖家、SaaS 团队、企业客服",
        outcome: "让 Agent 读取产品资料和常见问题，辅助客服回复、售后处理和知识库更新。",
        tools: ["知识库", "客服系统", "AI Agent"],
        difficulty: "进阶",
        timeSaved: "每天 1-3 小时",
        monetization: "高",
        steps: ["整理产品资料", "建立 FAQ 知识库", "设定回复边界", "生成客服草稿", "人工审核后发送"],
        promptExample: "适合用于售前咨询、价格异议、售后安抚、投诉处理和客服培训。",
        relatedPack: "客服知识库插件方案",
        href: "/skills/customer-service-plugin",
        installUrl: "mailto:hello@agentzhan.com?subject=我想获取 AI 客服知识库插件方案",
        installLabel: "获取方案",
      },
      {
        slug: "shopify-store-plugin",
        title: "Shopify 店铺运营插件",
        audience: "跨境电商卖家、独立站团队、品牌运营、电商客服",
        outcome: "让 Agent 辅助整理商品信息、生成详情页文案、分析订单问题和客服回复。",
        tools: ["Shopify", "电商运营", "AI Agent"],
        difficulty: "进阶",
        timeSaved: "每周 3-8 小时",
        monetization: "高",
        steps: ["连接 Shopify 店铺", "读取商品和订单", "生成商品文案", "分析客户问题", "输出运营建议"],
        promptExample: "适合用于商品上架、详情页优化、售后回复、活动文案和订单异常处理。",
        relatedPack: "Shopify AI 运营插件方案",
        href: "/skills/shopify-store-plugin",
        installUrl: "https://apps.shopify.com",
        installLabel: "Shopify App Store",
      },
      {
        slug: "stripe-payment-plugin",
        title: "Stripe 收款分析插件",
        audience: "SaaS 创业者、独立开发者、课程卖家、订阅制产品",
        outcome: "让 Agent 辅助查看收款、订阅、退款和客户付款状态，生成经营分析摘要。",
        tools: ["Stripe", "订阅收款", "AI Agent"],
        difficulty: "专业",
        timeSaved: "每周 1-3 小时",
        monetization: "高",
        steps: ["连接 Stripe", "读取付款和订阅数据", "识别异常订单", "生成收入摘要", "输出续费和流失分析"],
        promptExample: "适合用于 SaaS 收款分析、课程付款跟进、会员订阅监控和退款原因整理。",
        relatedPack: "Stripe 收款分析插件方案",
        href: "/skills/stripe-payment-plugin",
        installUrl: "https://marketplace.stripe.com",
        installLabel: "Stripe App Marketplace",
      },
    ],
  },
];

export const allSkills = skillBranches.flatMap((branch) =>
  branch.skills.map((skill) => ({ ...skill, branch: branch.title, branchSlug: branch.slug, color: branch.color })),
);

export function getSkillBySlug(slug: string) {
  return allSkills.find((skill) => skill.slug === slug);
}
